version: "3.8"
services: 
  miapp:
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
  mysql:  
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nodeapp
      - MYSQL_USER=joaquin
      - MYSQL_PASSWORD=123456
  