version: "3.8"
services: 
  miapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - mysql
    volumes:
      - .:/home/app
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
  mysql:  
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nodeapp
      - MYSQL_USER=joaquin
      - MYSQL_PASSWORD=123456
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - mysql
    command: tcp mysql:3306 -t 30s -i 250ms
